name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
    - name: Build with Gradle
      run: |
        ./gradlew aRelease
        ./gradlew aDebug
    - name: Upload build artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ matrix.os }}-artifact
        path: app/build/outputs
